"""first_init

Revision ID: 66e4efb0f6ec
Revises: 
Create Date: 2025-09-11 23:50:30.588837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66e4efb0f6ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_candidates',
    sa.Column('c_id', sa.Integer(), nullable=False),
    sa.Column('c_active', sa.Boolean(), nullable=False),
    sa.Column('c_name', sa.String(length=255), nullable=False),
    sa.Column('c_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('c_id')
    )
    op.create_table('t_students',
    sa.Column('s_id', sa.Integer(), nullable=False),
    sa.Column('s_code', sa.String(length=255), nullable=False),
    sa.Column('s_name', sa.String(length=255), nullable=False),
    sa.Column('s_active', sa.Boolean(), nullable=False),
    sa.Column('s_specialization', sa.String(length=255), nullable=True),
    sa.Column('s_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('s_id'),
    sa.UniqueConstraint('s_code')
    )
    op.create_table('t_votes',
    sa.Column('v_candidate_id', sa.Integer(), nullable=False),
    sa.Column('v_student_id', sa.Integer(), nullable=False),
    sa.Column('v_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['v_candidate_id'], ['t_candidates.c_id'], ),
    sa.ForeignKeyConstraint(['v_student_id'], ['t_students.s_id'], ),
    sa.PrimaryKeyConstraint('v_student_id'),
    sa.UniqueConstraint('v_student_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_votes')
    op.drop_table('t_students')
    op.drop_table('t_candidates')
    # ### end Alembic commands ###
