"""first_init

Revision ID: 7b194d515726
Revises: 66e4efb0f6ec
Create Date: 2025-09-11 23:54:12.293258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b194d515726'
down_revision: Union[str, None] = '66e4efb0f6ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_students', sa.Column('s_chat_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 't_students', ['s_chat_id'])
    op.create_unique_constraint(None, 't_votes', ['v_student_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_votes', type_='unique')
    op.drop_constraint(None, 't_students', type_='unique')
    op.drop_column('t_students', 's_chat_id')
    # ### end Alembic commands ###
